---
name: Test Ansible roles with Molecule
description: Run Molecule to test Ansible roles
runs:
  using: docker
  image: 'docker://local/molecule-image:1.0.0'
  env:
    ANSIBLE_ROLES_PATH: "../"
    ANSIBLE_ASYNC_DIR: "/tmp/.ansible_async"
    namespace: local
    image: fedora
    tag: latest
    command: test
    scenario: default
